name: Manual Trigger

on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      environment:
        required: true
        default: 'staging'
        type: choice
        options:
          - staging
          - production

permissions:
  pull-requests: write
  issues: write

jobs:
  time-displayed:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Storing template to display
        id: templating
        run: |
          echo "Here is my testing comment content" > temp.txt
          echo "plan_diff=$(cat temp.txt)" >> $GITHUB_OUTPUT

      - name: Show Variable
        run: |
          echo "${{ steps.templating.outputs.plan_diff }}"

      - name: Danger
        if: ${{ github.event_name == 'pull_request' }}
        uses: danger/danger-js@13.0.4
        with:
          # args: "--dangerfile artsy/peril-settings/org/allPRs.ts"
          args: "--dangerfile artsy/peril-settings/blob/main/org/allPRs.ts"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Deployment
        uses: actions/github-script@v3
        id: create-deployment
        with:
          script: |
            const deployment = await github.repos.createDeployment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: context.sha,
              environment: '${{ github.event.inputs.environment }}',
              required_contexts: []
            });
            return deployment.data.id;

      - name: Update Deployment Status
        uses: actions/github-script@v3
        with:
          script: |
            github.repos.createDeploymentStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              deployment_id: ${{ steps.create-deployment.outputs.result }},
              state: 'success',
              environment: '${{ github.event.inputs.environment }}',
              description: 'Deployment to ${{ github.event.inputs.environment }} succeeded'
            })
