name: Manual Trigger

on:
  pull_request:

permissions:
  pull-requests: write
  issues: write
  contents: write
  actions: write
  deployments: write

jobs:
  time-displayed:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Danger
        id: temp
        run: |
          echo 'global_diff<<EOF' >> $GITHUB_OUTPUT
          cat plan.txt >> $GITHUB_OUTPUT
          echo 'EOF' >> $GITHUB_OUTPUT
      - name: Printer
        run: |
          ehco "new step, but printing ${github.steps.outputs.temp.global_diff}"
      
