name: Manual Trigger

on:
  pull_request:

permissions:
  pull-requests: write
  issues: write
  contents: write
  actions: write
  deployments: write

jobs:
  time-displayed:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Danger
        id: temp
        run: |
          echo "+ \"ssm:GetParameter\", \n + \"ssm:GetParameters\", \n + \"ssm:GetParametersByPath\", \n+ \"ssm:DescribeParameters\", \n+ \"kms:Encrypt\", \n+ \"kms:Decrypt\", \n+ \"kms:GenerateDataKey*\"," >> global-diff.txt
          echo 'global_diff<<EOF' >> $GITHUB_OUTPUT
          cat global-diff.txt >> $GITHUB_OUTPUT
          echo 'EOF' >> $GITHUB_OUTPUT
      - name: Printer
        run: |
          echo "new step, but printing ${{ github.steps.outputs.temp.global_diff }}"
      
