
name: Manual Trigger

on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      environment:
        required: true
        default: 'staging'
        type: choice
        options: 
          - staging
          - production

permissions:
  pull-requests: write
  issues: write

jobs:
  time-displayed:
    environment: ${{ github.event.inputs.environment }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Storing template to display
        id: templating
        run: |
          echo "Here is my testing comment content" > temp.txt
          echo "plan_diff=$(cat temp.txt)" >> $GITHUB_OUTPUT

      - name: Show Variable
        run: |
          echo "${{ steps.templating.outputs.plan_diff }}"

      - name: Danger
        uses: danger/danger-js@13.0.4
         if: ${{ github.event_name == 'pull_request' }}
        with: 
          args: "--dangerfile artsy/peril-settings/org/allPRs.ts"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


      - name: Update Deployment Status
        uses: actions/github-script@v3
        with:
          script: |
            github.repos.createDeploymentStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              deployment_id: ${{ github.event.deployment.id }},
              state: 'success',
              environment: 'staging',
              description: 'Deployment to staging succeeded'
            })
    
