
name: Manual Trigger

on:
  workflow_dispatch:
    inputs:
      environment:
        required: true
        default: 'staging'
        type: choice
        options: 
          - staging
          - production

jobs:
  time-displayed:
    runs-on: ubuntu-latest
    steps:
      - name: Display current time
        run: |
          echo "Here is the the current system time $(date)"

  manual-approval-staging:
    needs: time-displayed
    runs-on: ubuntu-latest
    environment:
      name: staging
      url: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
    steps:
      - name: Await approval
        run: echo "Review the diff above and approve this deployment from the 'Environments' page."

  manual-approval-production:
    needs: time-displayed
    runs-on: ubuntu-latest
    environment: 
      name: production
      url: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
    steps:
      - name: Await approval
        run: echo "Review the diff above and approve this deployment from the 'Environments' page."
    
