name: Manual Trigger

on:
  pull_request:
  workflow_dispatch:
    inputs:
      environment:
        required: true
        default: 'staging'
        type: choice
        options:
          - staging
          - production

permissions:
  pull-requests: write
  issues: write
  contents: write
  actions: write
  deployments: write

jobs:
  time-displayed:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Danger
        if: ${{ github.event_name == 'pull_request' }}
        uses: danger/danger-js@13.0.4
        env:
          GITHUB_TOKEN: ${{ secrets.DANGER_GITHUB_API_TOKEN }}

      - name: Create Deployment
        uses: actions/github-script@v3
        id: create-deployment
        with:
          script: |
            const deployment = await github.repos.createDeployment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: context.sha,
              environment: 'staging',
              required_contexts: []
            });
            return deployment.data.id;

      - name: Update Deployment Status
        uses: actions/github-script@v3
        with:
          script: |
            github.repos.createDeploymentStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              deployment_id: ${{ steps.create-deployment.outputs.result }},
              state: 'success',
              environment: '${{ github.event.inputs.environment }}',
              description: 'Deployment to ${{ github.event.inputs.environment }} succeeded'
            })
