
name: Manual Trigger

on:
  pull_request:
  workflow_dispatch:
    inputs:
      environment:
        required: true
        default: 'staging'
        type: choice
        options: 
          - staging
          - production

jobs:
  time-displayed:
    runs-on: ubuntu-latest
    steps:
      - name: Display current time
        id: templating
        run: |
          echo "dhani is the man" > temp.txt
          echo "plan_diff=$(cat temp.txt)" >> $GITHUB_OUTPUT


      - name: Show Variable
        run: |
          echo "${{ steps.templating.outputs.plan_diff }}"

      - name: Create comment
        id: diff-comment
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.pull_request.number }}
          edit-mode: replace
          body: ${{ steps.template.outputs.result }}

      # - name: Render template
      #   id: template
      #   uses: chuhlomin/render-template@v1.4
      #   with:
      #     template: .github/comment-template.md
      #     vars: |
      #       foo: ${{ steps.my_step.outputs.my_variable }}
      #       bar: that
    
      # - name: Create comment
      #   uses: peter-evans/create-or-update-comment@v4
      #   with:
      #     issue-number: 1
      #     body: ${{ steps.template.outputs.result }}


    
