name: PUll REQUEST

on:
  pull_request:

permissions:
  pull-requests: write
  issues: write
  contents: write
  actions: write
  deployments: write


jobs:
  job-1:
    runs-on: ubuntu-latest
    if: false
    steps:
      - name: Checkout repository
        run: echo "Job 1 just ran!"

      
  display:
    runs-on: ubuntu-latest
    needs: job-1
    if: always()
    steps:
      - name: Printer
        run: |
          echo "new step, but printing ${{ github.ref_name }}"
      
