name: Manual Trigger

on:
  pull_request:

permissions:
  pull-requests: write
  issues: write
  contents: write
  actions: write
  deployments: write

jobs:
  set-up-outputs:
    runs-on: ubuntu-latest
    outputs:
      global-diff: ${{ steps.temp.outputs.global_diff }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Danger
        id: temp
        run: |
          echo 'global_diff<<EOF' >> $GITHUB_OUTPUT
          cat plan.txt >> $GITHUB_OUTPUT
          echo 'EOF' >> $GITHUB_OUTPUT
  display:
    runs-on: ubuntu-latest
    needs: set-up-outputs
    steps:
      - name: Printer
        run: |
          echo "new step, but printing ${{needs.temp.outputs.global-diff}}"
      
