name: Manual Trigger

on:
  pull_request:

permissions:
  pull-requests: write
  issues: write
  contents: write
  actions: write
  deployments: write

env:
  display-result: 'true'

jobs:
  job-1:
    runs-on: ubuntu-latest
    if: false
    steps:
      - name: Checkout repository
        run: echo "Job 1 just ran!"

      
  display:
    runs-on: ubuntu-latest
    needs: job-1
    if: always() && ${{ env.dispaly-result == 'true' }} 
    steps:
      - name: Printer
        run: |
          echo "new step, but printing ${{ github.ref_name }}"
      
