name: Manual Trigger

on:
  push:
    branches:
      - staging

jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      global-infra-updates: ${{ steps.outputs.global-infra-updates }}
      staging-infra-updates: ${{ steps.outputs.staging-infra-updates }}
    steps:
      - name: outputs
        run: |
          echo "global-infra-updates=false" >> $GITHUB_OUTPUT
          echo "staging-infra-updates=true" >> $GITHUB_OUTPUT

  global-print:
    runs-on: ubuntu-latest
    needs: check
    if: ${{ needs.check.outputs.global-infra-updates == 'tru' }}
    steps:
      - name: global print
        run: |
          echo "just to see if global is running"
  
  staging-print:
    needs: global-print
    runs-on: ubuntu-latest
    if: ${{
          needs.check.outputs.staging-infra-updates == 'true' &&
          github.ref_name == 'staging' &&
          (needs.check.outputs.global-infra-updates == 'false' || needs.global-print.result == 'success')
        }}
    steps:
      - name: print ref name
        run: echo "${{ github.ref_name }}"
