name: Manual Trigger

on:
  push:
    branches:
      - staging

jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      global-infra-updates: ${{ steps.outputs.global-infra-updates }}
      staging-infra-updates: ${{ steps.outputs.staging-infra-updates }}
    steps:
      - name: printing Ref nme
        run: |
          echo "The ref_name ==> ${{ github.ref_name }}"

      - name: outputs
        id: prime
        run: |
          echo "global-infra-updates=false" >> $GITHUB_OUTPUT
          echo "staging-infra-updates=true" >> $GITHUB_OUTPUT

      - name: print outputs
        run: |
          echo "global-infra-updates ${{ steps.prime.outputs.global-infra-updates }} && condition  ${{ steps.prime.outputs.global-infra-updates  == 'false' }}"
          echo "staging-infra-updates ${{ steps.prime.outputs.staging-infra-updates }} && condition  ${{ steps.prime.outputs.staging-infra-updates == 'true' }}"

  global-print:
    runs-on: ubuntu-latest
    needs: check
    if: ${{ needs.check.outputs.global-infra-updates == 'true' }}
    steps:
      - name: global print
        run: |
          echo "just to see if global is running"
  
  staging-print:
    needs: [global-print, check]
    runs-on: ubuntu-latest
    if: always() && ${{
          needs.check.outputs.staging-infra-updates == 'true' &&
          github.ref_name == 'staging' &&
          (needs.check.outputs.global-infra-updates == 'false' || needs.global-print.result == 'success')
        }}
    steps:
      - name: print ref name
        run: echo "${{ github.ref_name }}"
